export const VEHICLES = [
    {
        id: 0,
        name: "Toyota",
        image: "/assets/images/vitz.jpg",
        lot: 1234,
        model: "Vitz",
        exteriorcolor: "GRAY",
        interiorcolor: "BLACK",
        engine: "1.2L Petrol",
        country: "Japan",
        transmission: "Automatic",
        mileage: 65000,
        vin:"**********A054236",
        status: "Available",
        year: 2013,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        featured: false,
    },
    {
        id: 1,
        name: "Kia",
        image: "/assets/images/kia.jpg",
        model: "Morning",
        exteriorcolor: "GRAY",
        interiorcolor: "DARK BLUE",
        engine: "1.0L Petrol",
        country: "United States",
        transmission: "Automatic",
        mileage: 53000,
        vin:"**********A054236",
        status: "Available",
        year: 2010,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        featured: false
    },
    {
        id: 2,
        name: "Toyota",
        image: "/assets/images/yaris.png",
        model: "Yaris",
        exteriorcolor: "GRAY",
        interiorcolor: "RED",
        engine: "1.5L Petrol",
        country: "Japan",
        transmission: "Automatic",
        mileage: 65070,
        vin:"**********A054236",
        status: "Available",
        year: 2016,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        featured: false
    },
    {
        id: 3,
        name: "Hyundai",
        image: "/assets/images/elantra.jpeg",
        model: "Elantra",
        exteriorcolor: "RED",
        interiorcolor: "CREAM",
        engine: "1.5L Petrol",
        country: "Japan",
        transmission: "Automatic",
        mileage: 42500,
        vin:"**********A054241",
        status: "Available",
        year: 2012,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        featured: false
    },
    {
        id: 4,
        name: "Chevrolet",
        image: "/assets/images/aveo.jpg",
        model: "Aveo",
        exteriorcolor: "BLUE",
        interiorcolor: "BROWN",
        engine: "1.0L Petrol",
        country: "United States",
        transmission: "Automatic",
        mileage: 68500,
        vin:"**********A059836",
        status: "Available",
        year: 2012,
        description: "Aveo is for basic transportation and is attractive with lots of standard features.",
        featured: true,
    }
];